[log]
debug = true
filepath = "Runtime/zap.log"

[kafka-producer]
brokers = ["ubuntuvm:9092"]
topic = "test"
compressionType = 2
ack = 0
debug = true
clientid = "test-producer"

[kafka-consumer]
brokers = ["ubuntuvm:9092"]
topics = ["test","test1"]
groupId = "config-group-id"
version = "2.2.1"
debug = true
clientid = "test-consumer"

[emq]
addr = "ubuntuVM:1883"
user = "test"
passwd = "test"
cleansession = false
clientid = "test111"

[db]
host = "ubuntuVM"                #数据库连接地址
dbname = "iot_posmq"                 #数据库名称
user = "root"           #数据库用户名
passwd = "123456"   #数据库密码
port = "3306"                     #数据库端口号
debug = true
