[log]
debug = true
filepath = "Runtime/zap.log"

[kafka-producer]
brokers = ["ubuntuvm:9092"]
topic = "test1"
compression = true
async = false

[kafka-consumer]
brokers = ["ubuntuvm:9092"]
topic = "test1"
groupId = "config-group-id"
minbytes = 100
partition = 0

[emq]
addr = "ubuntuVM:1883"
user = "test"
passwd = "test"
cleansession = false
clientid = ""

[db]
host = "ubuntuVM"                #数据库连接地址
dbname = "iot_posmq"                 #数据库名称
user = "root"           #数据库用户名
passwd = "123456"   #数据库密码
port = "3306"                     #数据库端口号
debug = true
